//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroundOrganizer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroundOrganizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon business_color_books_icon_icons_com_53474 {
            get {
                object obj = ResourceManager.GetObject("business_color_books_icon_icons_com_53474", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] IGE {
            get {
                object obj = ResourceManager.GetObject("IGE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShemaFound {
            get {
                object obj = ResourceManager.GetObject("ShemaFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShemaLoads {
            get {
                object obj = ResourceManager.GetObject("ShemaLoads", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0;0;1;3.14
        ///1;0.01;1.06;3.23
        ///2;0.03;1.12;3.32
        ///3;0.04;1.18;3.41
        ///4;0.06;1.25;3.51
        ///5;0.08;1.32;3.61
        ///6;0.1;1.39;3.71
        ///7;0.12;1.47;3.82
        ///8;0.14;1.55;3.93
        ///9;0.16;1.64;4.05
        ///10;0.18;1.73;4.17
        ///11;0.21;1.83;4.29
        ///12;0.23;1.94;4.42
        ///13;0.26;2.05;4.55
        ///14;0.29;2.17;4.69
        ///15;0.32;2.3;4.84
        ///16;0.36;2.43;4.99
        ///17;0.39;2.57;5.15
        ///18;0.43;2.73;5.31
        ///19;0.47;2.89;5.48
        ///20;0.51;3.06;5.66
        ///21;0.56;3.24;5.84
        ///22;0.61;3.44;6.04
        ///23;0.66;3.65;6.24
        ///24;0.72;3.87;6.45
        ///25;0.78;4.11;6.67
        ///26;0.84;4.37;6.9
        ///27;0.91;4.64;7.14        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string tabl_5_5 {
            get {
                return ResourceManager.GetString("tabl_5_5", resourceCulture);
            }
        }
    }
}
